name: Generate Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - run: npm install

    - name: run generate-readme
      run: npm run generate-readme
    
    - name: git auto commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_message: generate readme


